# Generated by Django 4.2.9 on 2024-06-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentorregistration_delete_mentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorregistration',
            options={'verbose_name_plural': 'MentorRegistration'},
        ),
    ]
