# Generated by Django 4.2.9 on 2024-06-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_mentorregistration_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorregistration',
            old_name='area_of_intrest',
            new_name='area_of_interest',
        ),
    ]
