# Generated by Django 4.2.9 on 2024-06-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_rename_area_of_intrest_mentorregistration_area_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorregistration',
            name='registration_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mentorregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
