# Generated by Django 4.2.9 on 2024-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_mentorregistration_registration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorregistration',
            name='commitment_as_mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorregistration',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorregistration',
            name='intensive_mentoring_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentorregistration',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
