# Generated by Django 4.2.9 on 2024-06-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0009_fundraised'),
        ('mentor', '0006_mentorregistration_commitment_as_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorregistration',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district'),
        ),
        migrations.AlterField(
            model_name='mentorregistration',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.state'),
        ),
    ]
