# Generated by Django 4.2.9 on 2024-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0008_alter_mentorregistration_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorregistration',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
