# Generated by Django 4.2.9 on 2024-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequests',
            name='meeting_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequests',
            name='meeting_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequests',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrequests',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=50, null=True),
        ),
    ]
