# Generated by Django 4.2.9 on 2024-03-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingrequests_meeting_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequests',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrequests',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
