# Generated by Django 4.2.9 on 2024-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingrequests_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequests',
            name='status',
            field=models.CharField(blank=True, choices=[('start_up_request', 'start_up_request'), ('vc_accepted', 'vc_accepted'), ('scheduled', 'scheduled'), ('online_meeting_link_awaiting', 'online_meeting_link_awaiting'), ('start_up_reschedule', 'start_up_reschedule'), ('rejected', 'rejected')], max_length=50, null=True),
        ),
    ]
