# Generated by Django 4.2.9 on 2024-03-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meetingrequests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequests',
            name='next_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
