# Generated by Django 4.2.9 on 2024-04-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetingrequests_next_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingrequests',
            options={'verbose_name_plural': 'MeetingRequests'},
        ),
    ]
