# Generated by Django 4.2.9 on 2024-04-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meetingrequests_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingrequests',
            options={'verbose_name_plural': 'Meeting Requests'},
        ),
    ]
