# Generated by Django 4.2.9 on 2024-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meetingrequests_created_meetingrequests_meeting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequests',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
