# Generated by Django 4.2.9 on 2024-04-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbenfits',
            options={'verbose_name_plural': 'ProductBenfits'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='tangiblebenfits',
            options={'verbose_name_plural': 'TangibleBenfits'},
        ),
    ]
