# Generated by Django 4.2.9 on 2024-06-14 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcstartup_meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingRequest',
            new_name='vcstartup_MeetingRequest',
        ),
    ]
