# Generated by Django 4.2.9 on 2024-05-11 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollsRoyceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=255)),
                ('focus_area', models.CharField(max_length=255)),
                ('team_size', models.IntegerField()),
                ('team_composition', models.TextField()),
                ('solution_brief', models.TextField()),
                ('solution_uniqueness', models.TextField()),
                ('solution_sustainable_development_goals', models.TextField()),
                ('innovation_current_stage', models.CharField(max_length=255)),
                ('patent_status', models.CharField(max_length=255)),
                ('proposed_rc_research_papers_exist', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('proposed_rc_research_papers_count', models.IntegerField(blank=True, null=True)),
                ('proposed_rc_research_papers_links', models.TextField(blank=True, null=True)),
                ('proposed_rc_research_papers_files', models.FileField(blank=True, null=True, upload_to='proposed_rc_research_papers/')),
                ('timeframe', models.TextField()),
                ('expected_impacts_outcomes', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
