# Generated by Django 4.2.9 on 2024-02-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0003_alter_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
