# Generated by Django 4.2.9 on 2024-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0006_alter_areaofinterest_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryBusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial', models.IntegerField(default=0)),
            ],
        ),
    ]
