# Generated by Django 4.2.9 on 2024-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0007_primarybusinessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdevelopmentstage',
            name='description',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
