# Generated by Django 4.2.9 on 2024-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0008_productdevelopmentstage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRaised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial', models.IntegerField(default=0)),
            ],
        ),
    ]
