# Generated by Django 4.2.9 on 2024-05-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0038_merge_20240509_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='data_source',
            field=models.CharField(blank=True, choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo'), ('is_old', 'is_old')], default='registration', max_length=255, null=True),
        ),
    ]
