# Generated by Django 4.2.9 on 2024-02-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherregistrations',
            name='patents',
        ),
        migrations.AddField(
            model_name='researcherregistrations',
            name='patents',
            field=models.ManyToManyField(blank=True, null=True, to='registrations.patentinfo'),
        ),
    ]
