# Generated by Django 4.2.9 on 2024-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_vcregistrations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrations',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentregistrations',
            name='paper_published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
