# Generated by Django 4.2.9 on 2024-03-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_remove_researcherregistrations_patents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherregistrations',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('duplicate', 'duplicate'), ('archive', 'archive'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
