# Generated by Django 4.2.9 on 2024-01-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_industrycategory'),
        ('registrations', '0003_alter_industry_area_of_interest_for_collaboration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.industrycategory'),
        ),
        migrations.DeleteModel(
            name='IndustryCategory',
        ),
    ]
