# Generated by Django 4.2.9 on 2024-03-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_researcherregistrations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherregistrations',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
