# Generated by Django 4.2.9 on 2024-02-01 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0002_industrycategory'),
        ('registrations', '0004_alter_industry_industry_delete_industrycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('point_of_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('area_of_interest', models.ManyToManyField(to='datarepo.areaofinterest')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.industrycategory')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.state')),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='researcher_pictures/')),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('area_of_interest', models.ManyToManyField(to='datarepo.areaofinterest')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.institution')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('project_idea', models.TextField(blank=True, null=True)),
                ('area_of_interest', models.ManyToManyField(to='datarepo.areaofinterest')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.institution')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.state')),
            ],
        ),
        migrations.CreateModel(
            name='VCRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('area_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.areaofinterest')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district')),
                ('funding_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.preferredinvestmentstage')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.state')),
            ],
        ),
        migrations.RenameModel(
            old_name='StartUp',
            new_name='StartUpRegistrations',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='district',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='patents',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='research_areas',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='domain_of_interest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='vc',
            name='area_of_interest',
        ),
        migrations.RemoveField(
            model_name='vc',
            name='district',
        ),
        migrations.RemoveField(
            model_name='vc',
            name='preferred_investment_stage',
        ),
        migrations.RemoveField(
            model_name='vc',
            name='state',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RenameModel(
            old_name='Patent',
            new_name='PatentInfo',
        ),
        migrations.RenameModel(
            old_name='Publication',
            new_name='PublicationInfo',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='VC',
        ),
        migrations.AddField(
            model_name='researcherregistrations',
            name='patents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.patentinfo'),
        ),
        migrations.AddField(
            model_name='researcherregistrations',
            name='publications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.publicationinfo'),
        ),
        migrations.AddField(
            model_name='researcherregistrations',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.state'),
        ),
    ]
