# Generated by Django 4.2.9 on 2024-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_researcherregistrations_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/'),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('duplicate', 'duplicate'), ('archive', 'archive'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
