# Generated by Django 4.2.9 on 2024-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_startupregistrations_pitch_deck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='dpiit_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='market_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
