# Generated by Django 4.2.9 on 2024-02-06 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_industryregistrations_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryregistrations',
            name='registration_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
