# Generated by Django 4.2.9 on 2024-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_startupregistrations_dpiit_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='dpiit_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
