# Generated by Django 4.2.9 on 2024-03-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_startupregistrations_dpiit_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpRegistrationsCoFounders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.startupregistrations')),
            ],
        ),
    ]
