# Generated by Django 4.2.9 on 2024-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_industryregistrations_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryregistrations',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
