# Generated by Django 4.2.9 on 2024-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_startupregistrationscofounders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrationscofounders',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
    ]
