# Generated by Django 4.2.9 on 2024-03-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_alter_startupregistrations_dpiit_number'),
        ('registrations', '0008_alter_startupregistrationscofounders_gender'),
    ]

    operations = [
    ]
