# Generated by Django 4.2.9 on 2024-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_alter_startupregistrationscofounders_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='company_linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='startupregistrationscofounders',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='short_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
