# Generated by Django 4.2.9 on 2024-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_industryregistrations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryregistrations',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
