# Generated by Django 4.2.9 on 2024-02-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_alter_industryregistrations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrations',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
