# Generated by Django 4.2.9 on 2024-03-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_merge_20240316_0236'),
        ('registrations', '0010_startupregistrations_product_development_stage_and_more'),
    ]

    operations = [
    ]
