# Generated by Django 4.2.9 on 2024-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_studentregistrations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrations',
            name='registration_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
