# Generated by Django 4.2.9 on 2024-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_researcherregistrations_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='pitch_deck',
            field=models.URLField(blank=True, null=True),
        ),
    ]
