# Generated by Django 4.2.9 on 2024-03-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0007_primarybusinessmodel'),
        ('registrations', '0011_merge_20240319_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='Incubator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='customer_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='primary_business_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.primarybusinessmodel'),
        ),
    ]
