# Generated by Django 4.0.5 on 2024-02-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_alter_startupregistrations_pitch_deck'),
        ('registrations', '0011_studentregistrations_registration_id'),
    ]

    operations = [
    ]
