# Generated by Django 4.2.9 on 2024-03-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_startupregistrations_incubator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='Incubator',
            new_name='incubator',
        ),
    ]
