# Generated by Django 4.2.9 on 2024-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_merge_20240210_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='short_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
