# Generated by Django 4.2.9 on 2024-03-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0009_fundraised'),
        ('registrations', '0013_rename_incubator_startupregistrations_incubator'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='fund_raised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.fundraised'),
        ),
    ]
