# Generated by Django 4.2.9 on 2024-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_startupregistrations_short_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='founding_experince',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='market_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='required_ammount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
