# Generated by Django 4.2.9 on 2024-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_startupregistrations_fund_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='product_development_stage_document',
            field=models.FileField(blank=True, null=True, upload_to='product_development_stage_document/'),
        ),
    ]
