# Generated by Django 4.2.9 on 2024-03-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_startupregistrations_product_development_stage_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='fund_raised_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
