# Generated by Django 4.2.9 on 2024-02-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_alter_startupregistrations_pitch_deck_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='required_ammount',
            new_name='required_amount',
        ),
    ]
