# Generated by Django 4.2.9 on 2024-02-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_rename_required_ammount_startupregistrations_required_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='founding_experince',
            new_name='founding_experience',
        ),
    ]
