# Generated by Django 4.2.9 on 2024-02-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_rename_founding_experince_startupregistrations_founding_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcregistrations',
            name='deal_size_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vcregistrations',
            name='portfolio_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
