# Generated by Django 4.2.9 on 2024-03-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_vcregistrations_company_portfolio_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vcregistrations',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vcregistrations',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
