# Generated by Django 4.2.9 on 2024-03-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_alter_startupregistrations_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryregistrations',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcherregistrations',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrationscofounders',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vcregistrations',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
