# Generated by Django 5.0.2 on 2024-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0003_district_state'),
        ('registrations', '0019_studentregistrations_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherregistrations',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, null=True, to='datarepo.areaofinterest'),
        ),
    ]
