# Generated by Django 4.2.9 on 2024-02-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_remove_vcregistrations_deal_size_range_and_more'),
        ('registrations', '0020_alter_researcherregistrations_area_of_interest'),
    ]

    operations = [
    ]
