# Generated by Django 4.2.9 on 2024-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0009_fundraised'),
        ('registrations', '0020_vcregistrations_deal_size_range_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcregistrations',
            name='area_of_interest',
        ),
        migrations.RemoveField(
            model_name='vcregistrations',
            name='funding_stage',
        ),
        migrations.AddField(
            model_name='vcregistrations',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, null=True, to='datarepo.areaofinterest'),
        ),
        migrations.AddField(
            model_name='vcregistrations',
            name='funding_stage',
            field=models.ManyToManyField(blank=True, null=True, to='datarepo.preferredinvestmentstage'),
        ),
    ]
