# Generated by Django 4.2.9 on 2024-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_remove_vcregistrations_area_of_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
