# Generated by Django 4.2.9 on 2024-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_startupregistrations_is_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
    ]
