# Generated by Django 4.2.9 on 2024-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_startupregistrations_is_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='is_old',
            field=models.BooleanField(default=False),
        ),
    ]
