# Generated by Django 4.2.9 on 2024-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_vcregistrations_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentinfo',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patentinfo',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicationinfo',
            name='journal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
