# Generated by Django 4.2.9 on 2024-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_alter_patentinfo_number_alter_patentinfo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherregistrations',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcherregistrations',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcherregistrations',
            name='registration_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
