# Generated by Django 4.2.9 on 2024-04-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0026_alter_researcherregistrations_highest_qualification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryregistrations',
            options={'verbose_name_plural': 'IndustryRegistrations'},
        ),
        migrations.AlterModelOptions(
            name='researcherregistrations',
            options={'verbose_name_plural': 'ResearcherRegistrations'},
        ),
        migrations.AlterModelOptions(
            name='startupregistrations',
            options={'verbose_name_plural': 'StartUpRegistrations'},
        ),
        migrations.AlterModelOptions(
            name='startupregistrationscofounders',
            options={'verbose_name_plural': 'StartUpRegistrationsCoFounders'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrations',
            options={'verbose_name_plural': 'StudentRegistrations'},
        ),
        migrations.AlterModelOptions(
            name='vcregistrations',
            options={'verbose_name_plural': 'VCRegistrations'},
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
    ]
