# Generated by Django 4.2.9 on 2024-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_alter_industryregistrations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
        migrations.AddField(
            model_name='startupregistrationscofounders',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
        migrations.AddField(
            model_name='studentregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
    ]
