# Generated by Django 4.2.9 on 2024-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0028_industryregistrations_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='company_linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='data_source',
            field=models.CharField(blank=True, choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255, null=True),
        ),
    ]
