# Generated by Django 4.2.9 on 2024-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0028_industryregistrations_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupregistrations',
            name='company_linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
