# Generated by Django 4.2.9 on 2024-04-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0029_remove_startupregistrationscofounders_data_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industryregistrations',
            options={'verbose_name_plural': 'Industry Registrations'},
        ),
        migrations.AlterModelOptions(
            name='researcherregistrations',
            options={'verbose_name_plural': 'Researcher Registrations'},
        ),
        migrations.AlterModelOptions(
            name='startupregistrations',
            options={'verbose_name_plural': 'StartUp Registrations'},
        ),
        migrations.AlterModelOptions(
            name='startupregistrationscofounders',
            options={'verbose_name_plural': 'StartUp Registrations CoFounders'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrations',
            options={'verbose_name_plural': 'Student Registrations'},
        ),
        migrations.AlterModelOptions(
            name='vcregistrations',
            options={'verbose_name_plural': 'VC Registrations'},
        ),
    ]
