# Generated by Django 4.2.9 on 2024-04-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0029_alter_startupregistrations_company_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industryregistrations',
            old_name='data_source',
            new_name='data_source_one',
        ),
        migrations.RemoveField(
            model_name='startupregistrationscofounders',
            name='data_source',
        ),
    ]
