# Generated by Django 4.2.9 on 2024-04-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0030_rename_data_source_industryregistrations_data_source_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryregistrations',
            name='data_source_one',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='studentregistrations',
            name='data_source',
        ),
    ]
