# Generated by Django 4.2.9 on 2024-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0030_alter_industryregistrations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcregistrations',
            name='fund_type',
            field=models.CharField(blank=True, choices=[('angel_investor', 'Angel Investor'), ('angel_network', 'Angel Network'), ('venture_capital', 'Venture Capital Fund'), ('family_office', 'Family Office'), ('corporate_vc', 'Corporate Venture Capital')], default=None, max_length=255, null=True),
        ),
    ]
