# Generated by Django 4.2.9 on 2024-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_vcregistrations_fund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrations',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentregistrations',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentregistrations',
            name='project_guide_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
