# Generated by Django 4.2.9 on 2024-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_remove_industryregistrations_data_source_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
        migrations.AddField(
            model_name='studentregistrations',
            name='data_source',
            field=models.CharField(choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo')], default='registration', max_length=255),
        ),
    ]
