# Generated by Django 4.2.9 on 2024-05-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0009_fundraised'),
        ('registrations', '0032_studentregistrations_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupregistrations',
            options={'verbose_name_plural': 'Startup Registrations'},
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='customer_size',
            new_name='client_customer_size',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='description',
            new_name='company_description',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='product_development_stage',
            new_name='development_stage',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='required_amount',
            new_name='funding_request_amount',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='incubator',
            new_name='incubator_associated',
        ),
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='founding_year',
            new_name='year_of_establishment',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='email',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='founder_names',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='founding_experience',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='fund_raised_value',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='funding_stage',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='is_old',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='market_size',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='product_development_stage_document',
        ),
        migrations.RemoveField(
            model_name='startupregistrations',
            name='short_video',
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='development_stage_document',
            field=models.FileField(blank=True, null=True, upload_to='development_stage_document/'),
        ),
        migrations.AddField(
            model_name='startupregistrations',
            name='preferred_investment_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.preferredinvestmentstage'),
        ),
        migrations.AlterField(
            model_name='startupregistrations',
            name='data_source',
            field=models.CharField(blank=True, choices=[('csv', 'csv'), ('registration', 'registration'), ('demo', 'demo'), ('is_old', 'is_old')], default='registration', max_length=255, null=True),
        ),
    ]
