# Generated by Django 4.2.9 on 2024-05-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0033_alter_startupregistrations_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='co_founder_count',
            new_name='co_founders_count',
        ),
    ]
