# Generated by Django 4.2.9 on 2024-05-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0034_rename_co_founder_count_startupregistrations_co_founders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='fund_raised_input',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
