# Generated by Django 4.2.9 on 2024-05-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0035_startupregistrations_fund_raised_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='incubator_associated',
            new_name='incubators_associated',
        ),
    ]
