# Generated by Django 4.2.9 on 2024-05-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0036_rename_incubator_associated_startupregistrations_incubators_associated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startupregistrations',
            old_name='website',
            new_name='company_website',
        ),
    ]
