# Generated by Django 4.2.9 on 2024-05-09 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0032_industryregistrations_data_source_and_more'),
        ('registrations', '0037_rename_website_startupregistrations_company_website'),
    ]

    operations = [
    ]
