# Generated by Django 4.2.9 on 2024-06-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeconnect', '0003_rename_meeting_link_meetingrequest_meeting_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='meeting_details',
            field=models.CharField(default='', max_length=255),
        ),
    ]
