# Generated by Django 4.2.9 on 2024-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'superadmin'), (2, 'admin'), (3, 'staff'), (4, 'industry'), (5, 'researcher'), (6, 'startup'), (7, 'student'), (8, 'vc')], default=8),
        ),
    ]
