# Generated by Django 4.2.9 on 2024-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='patents',
        ),
        migrations.AddField(
            model_name='researcher',
            name='patents',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.patent'),
        ),
    ]
