# Generated by Django 4.2.9 on 2024-03-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_researcher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vc',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
