# Generated by Django 4.2.9 on 2024-03-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_startup_approved_vc_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vc',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vc',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
