# Generated by Django 4.2.9 on 2024-03-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_startup_name_alter_vc_firm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vc',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
