# Generated by Django 4.2.9 on 2024-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_startup_short_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founding_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='registration_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='required_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
