# Generated by Django 4.2.9 on 2024-05-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0009_fundraised'),
        ('profiles', '0006_alter_industry_mobile_alter_researcher_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='co_founder_count',
            new_name='co_founders_count',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='description',
            new_name='company_description',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='required_amount',
            new_name='funding_request_amount',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='funding_stage',
            new_name='preferred_investment_stage',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='founding_year',
            new_name='year_of_establishment',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founding_experience',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='market_size',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='short_video',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='website',
        ),
        migrations.AddField(
            model_name='startup',
            name='client_customer_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='company_linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='development_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.productdevelopmentstage'),
        ),
        migrations.AddField(
            model_name='startup',
            name='development_stage_document',
            field=models.FileField(blank=True, null=True, upload_to='development_stage_document/'),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_raised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.fundraised'),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_raised_input',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='incubators_associated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='primary_business_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.primarybusinessmodel'),
        ),
        migrations.AddField(
            model_name='startup',
            name='reveune_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.revenuestage'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/'),
        ),
    ]
