# Generated by Django 4.2.9 on 2024-02-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_startup_founding_experience_startup_founding_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='registration_id',
        ),
    ]
