# Generated by Django 4.2.9 on 2024-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_co_founder_count_startup_co_founders_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='data_source',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
