# Generated by Django 4.2.9 on 2024-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_startup_registration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='founding_experience',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='founding_year',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='market_size',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='required_amount',
        ),
        migrations.AlterField(
            model_name='startup',
            name='short_video',
            field=models.FileField(blank=True, null=True, upload_to='short_video/'),
        ),
    ]
