# Generated by Django 4.2.9 on 2024-05-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_student_data_source_student_gender_student_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
