# Generated by Django 4.2.9 on 2024-02-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_startup_founding_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founding_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='market_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='required_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='short_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
