# Generated by Django 4.2.9 on 2024-05-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_industry_approved_industry_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vc',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
