# Generated by Django 4.2.9 on 2024-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_startup_founding_experience_startup_founding_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='pitch_deck',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='short_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
