# Generated by Django 4.2.9 on 2024-05-20 12:17

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_vc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paper_published',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vc',
            name='company_portfolio_document',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_documents/', validators=[profiles.models.validate_file_size]),
        ),
    ]
