# Generated by Django 4.2.9 on 2024-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_startup_pitch_deck_alter_startup_short_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vc',
            name='deal_size_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vc',
            name='portfolio_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
