# Generated by Django 4.2.9 on 2024-02-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_vc_deal_size_range_vc_deal_size_range_max_and_more'),
        ('profiles', '0013_student_email'),
    ]

    operations = [
    ]
