# Generated by Django 4.2.9 on 2024-06-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0009_fundraised'),
        ('profiles', '0014_remove_vc_area_of_interest_remove_vc_funding_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'superadmin'), (2, 'admin'), (3, 'staff'), (4, 'industry'), (5, 'researcher'), (6, 'startup'), (7, 'student'), (8, 'vc'), (9, 'mentor')], default=8),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer not to say')], max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='mentor_profile_pictures')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_bio', models.FileField(blank=True, null=True, upload_to='mentor_bios')),
                ('certified_mentor', models.BooleanField(blank=True, null=True)),
                ('functional_areas_of_expertise', models.CharField(blank=True, max_length=255, null=True)),
                ('mentoring_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('motivation_for_mentoring', models.CharField(blank=True, max_length=255, null=True)),
                ('category_represent_you', models.CharField(blank=True, max_length=255, null=True)),
                ('mentees_journey', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('area_of_intrest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.areaofinterest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mentor',
            },
        ),
    ]
