# Generated by Django 4.2.9 on 2024-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_user_user_role_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
