# Generated by Django 4.2.9 on 2024-06-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_mentor_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='area_of_intrest',
            new_name='area_of_interest',
        ),
    ]
