# Generated by Django 4.2.9 on 2024-06-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_mentor_district_alter_mentor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='updated_bio',
            field=models.FileField(blank=True, null=True, upload_to='mentor_bios/'),
        ),
    ]
