# Generated by Django 4.2.9 on 2024-06-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonproposal',
            name='focus_area',
        ),
    ]
