# Generated by Django 4.2.9 on 2024-02-23 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innovation_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='innovationchallengeoutcomes',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengeobjectives',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengeevaluationcriteria',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengeeligibilitycriteria',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengedetails',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='challenge_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.challengescategory'),
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='challenges_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.challengesubcategory'),
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengesubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.challengescategory'),
        ),
    ]
