# Generated by Django 4.2.9 on 2024-03-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0004_areaofinterest_is_approved'),
        ('innovation_challenges', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationChallengeOperationalCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationChallengeOtherRequriments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationChallengeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationChallengeTangibleOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InnovationTargetBeneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='challengesubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='innovationchallengeoutcomes',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='innovationchallenge',
            name='challenge_category',
        ),
        migrations.RemoveField(
            model_name='innovationchallenge',
            name='challenges_sub_category',
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, null=True, to='datarepo.areaofinterest'),
        ),
        migrations.AddField(
            model_name='innovationchallengedetails',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChallengesCategory',
        ),
        migrations.DeleteModel(
            name='ChallengeSubCategory',
        ),
        migrations.DeleteModel(
            name='InnovationChallengeOutcomes',
        ),
        migrations.AddField(
            model_name='innovationtargetbeneficiaries',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengetangibleoutcomes',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengerequirements',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengeotherrequriments',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
        migrations.AddField(
            model_name='innovationchallengeoperationalcapabilities',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_challenges.innovationchallenge'),
        ),
    ]
