# Generated by Django 4.2.9 on 2024-03-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_researcher_gender'),
        ('innovation_challenges', '0003_innovationchallengeoperationalcapabilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationchallengedetails',
            name='funding_details',
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.industry'),
        ),
    ]
