# Generated by Django 4.2.9 on 2024-03-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_challenges', '0004_remove_innovationchallengedetails_funding_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationchallenge',
            name='status',
            field=models.CharField(choices=[('active', 'archived')], default='active', max_length=100),
        ),
    ]
