# Generated by Django 4.2.9 on 2024-03-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_challenges', '0005_innovationchallenge_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InnovationChallengeProposalTeam',
            new_name='InnovationChallengeProposalExpertsInvolved',
        ),
        migrations.RenameModel(
            old_name='InnovationChallengeProposalMilestones',
            new_name='InnovationChallengeProposalSolutionAdvantages',
        ),
        migrations.RenameModel(
            old_name='InnovationChallengeProposalBenfits',
            new_name='InnovationChallengeProposalTangibleBenfits',
        ),
        migrations.RenameField(
            model_name='innovationchallengeproposal',
            old_name='market_domain',
            new_name='implementation_time',
        ),
        migrations.RemoveField(
            model_name='innovationchallengeproposalfiles',
            name='notes',
        ),
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='solution_readiness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='value_proposition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InnovationChallengeProposalDetails',
        ),
    ]
