# Generated by Django 4.2.9 on 2024-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_challenges', '0006_rename_innovationchallengeproposalteam_innovationchallengeproposalexpertsinvolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationchallenge',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('submitted', 'submitted')], default='active', max_length=100),
        ),
    ]
