# Generated by Django 4.2.9 on 2024-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_challenges', '0007_alter_innovationchallenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationchallengeproposal',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('archived', 'archived'), ('submitted', 'submitted')], default='submitted', max_length=100),
        ),
    ]
