# Generated by Django 4.2.9 on 2024-03-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0004_areaofinterest_is_approved'),
        ('innovation_challenges', '0008_innovationchallengeproposal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationchallenge',
            name='area_of_interest',
        ),
        migrations.AddField(
            model_name='innovationchallenge',
            name='area_of_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.areaofinterest'),
        ),
    ]
